# posts api

# add a new post
POST http://localhost:3000/api/post
Content-Type: application/json

{
    "title": "Hello World",
    "body": "Hi everyone",
    "sender": "User234"
}

###

# get all posts
GET http://localhost:3000/api/post

###

# get a post by ID
GET http://localhost:3000/api/post/6742fbd9520df4b4a871b223

###

# get posts by sender
GET http://localhost:3000/api/post/sender/post?sender=User123

###

# update a post
PUT http://localhost:3000/api/post/6742fbd9520df4b4a871b223
Content-Type: application/json

{
    "title": "Updated post",
    "body": "How are you"
}
###
  
# comments api

# add a new comment
POST http://localhost:3000/api/comment
Content-Type: application/json

{
    "postId": "6742fbd9520df4b4a871b223",
    "body": "This is a new comment",
    "author": "User234"
}

###

# get all comments for a post
GET http://localhost:3000/api/comment/6742fbd9520df4b4a871b223

###

# update a comment
PUT http://localhost:3000/api/comment/6742fc09520df4b4a871b229
Content-Type: application/json

{
    "body": "Updated comment content"
}

###

# delete a comment
DELETE http://localhost:3000/api/comment/6742fc09520df4b4a871b229